natal/urls.py
from django.urls import path

from . import views
from .views import formulario, sucesso, entrada, teste, visualizar_tabela, salvar_desc, visualizar_tabela2

urlpatterns = [
            path('entrada/', entrada, name='entrada'),
            path('formulario/', formulario, name='formulario'),
            path('sucesso/', sucesso, name='sucesso'),
			path('teste/', teste, name='teste'),
			path('visualizar-tabela/', visualizar_tabela, name='visualizar_tabela'),
			path('visualizar-tabela2/', visualizar_tabela2, name='visualizar_tabela2'),
			path('salvar_desc/', salvar_desc, name='salvar_desc'),
            ]

natal/models.py
from django.db import models

# Create your models here.
# minha_aplicacao/models.py
#from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    idade = models.IntegerField()

class Descrever(models.Model):
    quem = models.CharField(max_length=100)
    descricao = models.CharField(max_length=256)
    
class Entrada(models.Model):
    chave = models.CharField(max_length=25)
    
class AmigoSecreto(models.Model):
    chave = models.CharField(max_length=25)
    descricao = models.CharField(max_length=256)
    nome = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    amigo = models.CharField(max_length=100)

class Teste(models.Model):
    chave = models.CharField(max_length=25)
    nome = models.CharField(max_length=25)
    amigo = models.CharField(max_length=25)
    
class AmigoSecretoTeste2(models.Model):
    chave = models.CharField(max_length=25)
    descricao = models.CharField(max_length=256)
    nome = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    amigo = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    enviou_desc = models.CharField(max_length=10)
    enviou_amigo = models.CharField(max_length=10)

  

natal/forms.py
# minha_aplicacao/forms.py
#from django import forms
from django.forms import ModelForm, Textarea
from .models import Pessoa, Descrever, Entrada

class PessoaForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = ['nome', 'idade']

class DescreverForm(ModelForm):
    class Meta:
        model = Descrever
        fields = ['quem', 'descricao']
        widgets = {
            "descricao": Textarea(attrs={"cols": 47, "rows": 8}),
        }

class EntradaForm(ModelForm):
    class Meta:
        model = Entrada
        fields = ['chave']
        

natal/views.py
# minha_aplicacao/views.py
from django.shortcuts import render, redirect
from .forms import PessoaForm, EntradaForm, DescreverForm
from django.db import models
from .models import Teste, AmigoSecretoTeste2

def entrada(request):
        form = EntradaForm()
        return render(request, 'entrada.html', {'form': form})

def formulario(request):
        req = request.GET
        #req = request.POST
        getcha = req['chave']
        try:                
                dados = AmigoSecretoTeste2.objects.get(chave=getcha)
        except:
                dados = {'autor':'Não Encontrado', 'descricao': '', 'chave': ''}
                
        pessoa = dados.autor
                
        if request.method == 'POST':
                    form = DescreverForm(request.POST)
                    if form.is_valid():
                            form.save()
                            return render(request, 'teste.html')
                    else:
                              return render(request, 'formulario.html', {'form': form})  
        else:
                    form = DescreverForm(instance=dados)
                    return render(request, 'formulario.html', {'form': form, 'pessoa': pessoa, 'chave': getcha})

def sucesso(request):
        return render(request, 'sucesso.html')

def teste(request):
        req = request.GET
        getcha = req['chave']
        try:                
                dados = Teste.objects.get(chave=getcha)
        except:
                dados = {'nome':'Não Encontrado'}        
        return render(request, 'teste.html', {'dados': dados, 'getcha': getcha})

def visualizar_tabela(request):
    dados_tabela = AmigoSecretoTeste2.objects.all()  # Obtém todos os objetos da tabela
    return render(request, 'tabela.html', {'dados_tabela': dados_tabela})

def visualizar_tabela2(request):
    dados_tabela = AmigoSecretoTeste2.objects.all()  # Obtém todos os objetos da tabela
    return render(request, 'tabela2.html', {'dados_tabela': dados_tabela,})

def salvar_desc(request):
        req = request.POST
        desc = req['descricao']
        getcha = req['chave']
        
        ast = AmigoSecretoTeste2.objects.get(chave=getcha)
        ast.descricao = desc
        ast.enviou_desc = str(len(desc))
        ast.save(update_fields=['descricao', 'enviou_desc'])
        
        return render(request, 'sucesso.html')

natal/templates/entrada.html
  <!-- minha_aplicacao/templates/entrada.html -->

  <!DOCTYPE html>
  <html lang="en">
	  <head>
		      <meta charset="UTF-8">
		          <meta name="viewport" content="width=device-width, initial-scale=1.0">
			      <title>Formulário Natalino</title>
			          <style>
        body {
		            font-family: 'Arial', sans-serif;
			                background-color: #f5f5f5;
					            margin: 0;
						                padding: 0;
								            display: flex;
									                justify-content: center;
											            align-items: center;
												                height: 100vh;
														        }

	        form {
			            background-color: #fff;
				                padding: 20px;
						            border-radius: 10px;
							                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
									            max-width: 400px;
										                width: 100%;
												        }

		        h1 {
				            text-align: center;
					                color: #d9534f;
							        }

			        label {
					            display: block;
						                margin: 10px 0 5px;
								            color: #333;
									            }

				        input[type="text"],
					        input[type="number"] {
							            width: 100%;
								        padding: 10px;
										margin-bottom: 10px;
										box-sizing: border-box;
										border: 1px solid #ccc;
										border-radius: 4px;
										}

						        button {
								            background-color: #d9534f;
									                color: #fff;
											            padding: 10px;
												                border: none;
														            border-radius: 4px;
															                cursor: pointer;
																	            width: 100%;
																		            }

							        button:hover {
									            background-color: #c9302c;
										            }
								    </style>
	  </head>
	  <body>
		      <form method="post" action="{% url 'formulario' %}">
			              {% csrf_token %}
				              <h1>Amigo Bem Secreto</h1>
					              <label for="id_chave">Chave:</label>
						              {{ form.chave }}
								  <button type="submit">Abrir</button>
				</form>
	  </body>
  </html>

natal/templates/formulario.html
  <!-- minha_aplicacao/templates/formulario.html -->

  <!DOCTYPE html>
  <html lang="en">
	  <head>
		      <meta charset="UTF-8">
		          <meta name="viewport" content="width=device-width, initial-scale=1.0">
			      <title>Formulário Natalino</title>
			          <style>
        body {
		            font-family: 'Arial', sans-serif;
			                background-color: #f5f5f5;
					            margin: 0;
						                padding: 0;
								            display: flex;
									                justify-content: center;
											            align-items: center;
												                height: 100vh;
														        }

	        form {
			            background-color: #fff;
				                padding: 20px;
						            border-radius: 10px;
							                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
									            max-width: 400px;
										                width: 100%;
												        }

		        h1 {
				            text-align: center;
					                color: #d9534f;
							        }

			        label {
					            display: block;
						                margin: 10px 0 5px;
								            color: #333;
									            }

				        input[type="text"],
					        input[type="number"] {
							            width: 100%;
								                padding: 10px;
										            margin-bottom: 10px;
											                box-sizing: border-box;
													            border: 1px solid #ccc;
														                border-radius: 4px;
																        }
                  textarea {							            
										            margin-bottom: 10px;
											                box-sizing: border-box;
													            border: 1px solid #ccc;
														                border-radius: 4px;
																        }

						        button {
								            background-color: #d9534f;
									                color: #fff;
											            padding: 10px;
												                border: none;
														            border-radius: 4px;
															                cursor: pointer;
																	            width: 100%;
																		            }

							        button:hover {
									            background-color: #c9302c;
										            }
								    </style>
	  </head>
	  <body>
		      <form method="post" action="{% url 'salvar_desc' %}">
			              {% csrf_token %}
                    <input type="hidden" name="chave" value={{chave}}>
				              <h1>Amigo Bem Secreto</h1>					              
            <label for="id_descricao">Você deve descrever: <b>{{pessoa}}</b><br>
                              Escreva a sua descrição em poucas palavras.<br> Lembre que isso é tudo que o amigo secreto dessa pessoa irá receber, então diga o que julgar suficiente para dar uma boa ideia de quem é...<br> ...mas não entregue muito fácil!<br> A dúvida é a melhor parte da brincadeira.</label>
								              {{ form.descricao }}
									              <button type="submit">Salvar</button>
										          </form>
	  </body>
  </html>

natal/templates/sucesso.html
<!-- minha_aplicacao/templates/sucesso.html -->
<h2>Formulário enviado com sucesso!</h2>

natal/templates/tabela.html
  <!-- minha_aplicacao/templates/entrada.html -->

  <!DOCTYPE html>
  <html lang="en">
	  <head>
		      <meta charset="UTF-8">
		          <meta name="viewport" content="width=device-width, initial-scale=1.0">
			      <title>Formulário Natalino</title>
			          <style>
        body {
		            font-family: 'Arial', sans-serif;
			                background-color: #f5f5f5;
					            margin: 0;
						                padding: 0;
								            display: flex;
									                justify-content: center;
											            align-items: center;
												                height: 100vh;
														        }

	        form {
			            background-color: #fff;
				                padding: 20px;
						            border-radius: 10px;
							                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
									            max-width: 400px;
										                width: 100%;
												        }

		        h1 {
				            text-align: center;
					                color: #d9534f;
							        }

			        label {
					            display: block;
						                margin: 10px 0 5px;
								            color: #333;
									            }

				        input[type="text"],
					        input[type="number"] {
							            width: 100%;
								        padding: 10px;
										margin-bottom: 10px;
										box-sizing: border-box;
										border: 1px solid #ccc;
										border-radius: 4px;
										}

						        button {
								            background-color: #d9534f;
									                color: #fff;
											            padding: 10px;
												                border: none;
														            border-radius: 4px;
															                cursor: pointer;
																	            width: 100%;
																		            }

							        button:hover {
									            background-color: #c9302c;
										            }
								    </style>
	  </head>
	  <body>
      <h1>Dados da Tabela</h1>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>chave</th>
                <th>descricao</th>
                <th>nome</th>
              <th>autor</th>
              <th>amigo</th>
              <th>email</th>
              <th>enviou_desc</th>
              <th>enviou_amigo</th>
            </tr>
        </thead>
        <tbody>
            {% for item in dados_tabela %}
            <tr>
              <td>{{item.ID}}</td>
                <td>{{item.chave}}</td>
                <td>{{item.descricao}}</td>
                <td>{{item.nome}}</td>
              <td>{{item.autor}}</td>
              <td>{{item.amigo}}</td>
              <td>{{item.email}}</td>
              <td>{{item.enviou_desc}}</td>
              <td>{{item.enviou_amigo}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
	  </body>
  </html>

natal/templates/tabela2.html
  <!-- minha_aplicacao/templates/entrada.html -->

  <!DOCTYPE html>
  <html lang="en">
	  <head>
		      <meta charset="UTF-8">
		          <meta name="viewport" content="width=device-width, initial-scale=1.0">
			      <title>Formulário Natalino</title>
			          <style>
        body {
		            font-family: 'Arial', sans-serif;
			                background-color: #f5f5f5;
					            margin: 0;
						                padding: 0;
								            display: flex;
									                justify-content: center;
											            align-items: center;
												                height: 100vh;
														        }

	        form {
			            background-color: #fff;
				                padding: 20px;
						            border-radius: 10px;
							                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
									            max-width: 400px;
										                width: 100%;
												        }

		        h1 {
				            text-align: center;
					                color: #d9534f;
							        }

			        label {
					            display: block;
						                margin: 10px 0 5px;
								            color: #333;
									            }

				        input[type="text"],
					        input[type="number"] {
							            width: 100%;
								        padding: 10px;
										margin-bottom: 10px;
										box-sizing: border-box;
										border: 1px solid #ccc;
										border-radius: 4px;
										}

						        button {
								            background-color: #d9534f;
									                color: #fff;
											            padding: 10px;
												                border: none;
														            border-radius: 4px;
															                cursor: pointer;
																	            width: 100%;
																		            }

							        button:hover {
									            background-color: #c9302c;
										            }
								    </style>
	  </head>
	  <body>
      <h1>Dados da Tabela</h1>
    <table border="1">
        <thead>
            <tr>
                <th>nome</th>
              <th>email</th>
              <th>enviou_desc</th>
              <th>enviou_amigo</th>
            </tr>
        </thead>
        <tbody>
            {% for item in dados_tabela %}
            <tr>              
                <td>{{item.nome}}</td>
              <td>{{item.email}}</td>
              <td>{{item.enviou_desc}}</td>
              <td>{{item.enviou_amigo}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
	  </body>
  </html>

natal/templates/teste.html
  <!-- minha_aplicacao/templates/entrada.html -->

  <!DOCTYPE html>
  <html lang="en">
	  <head>
		      <meta charset="UTF-8">
		          <meta name="viewport" content="width=device-width, initial-scale=1.0">
			      <title>Formulário Natalino</title>
			          <style>
        body {
		            font-family: 'Arial', sans-serif;
			                background-color: #f5f5f5;
					            margin: 0;
						                padding: 0;
								            display: flex;
									                justify-content: center;
											            align-items: center;
												                height: 100vh;
														        }

	        form {
			            background-color: #fff;
				                padding: 20px;
						            border-radius: 10px;
							                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
									            max-width: 400px;
										                width: 100%;
												        }

		        h1 {
				            text-align: center;
					                color: #d9534f;
							        }

			        label {
					            display: block;
						                margin: 10px 0 5px;
								            color: #333;
									            }

				        input[type="text"],
					        input[type="number"] {
							            width: 100%;
								        padding: 10px;
										margin-bottom: 10px;
										box-sizing: border-box;
										border: 1px solid #ccc;
										border-radius: 4px;
										}

						        button {
								            background-color: #d9534f;
									                color: #fff;
											            padding: 10px;
												                border: none;
														            border-radius: 4px;
															                cursor: pointer;
																	            width: 100%;
																		            }

							        button:hover {
									            background-color: #c9302c;
										            }
								    </style>
	  </head>
	  <body>
      {{getcha}}<br>
	  </body>
  </html>